#! /home/davidv/.virtualenvs/automateBS/bin/python

import os, docx

def throwInvite(guestsFile):
	guestList = open(guestsFile, 'r')
	print(guestList.readline())
	print(guestList.readline())



throwInvite('guests.txt')
